### ISSUE TITLE
Update documentation with renamed items on ticket #17

### ISSUE THREAD

**Issue by ivanjunckes** [JNOSQL/artemis#19]
Update documentation with renamed items on ticket #17
CrudRepository -> Repository
CrudRepositoryAsync -> RepositoryAsync
DocumentRepository -> DocumentTemplate
ColumnRepository -> ColumnTemplate
DocumentRepositoryAsync -> DocumentTemplateAsync
ColumnRepositoryAsync -> ColumnTemplateAsync

**Comment by otaviojava** [comment]
Fixed
